### ISSUE TITLE
Alt references to be added

### ISSUE THREAD

**Issue by Razikd29** [pokeclicker/pokeclicker-translations#5]
While going through the json file for translation, I noticed that many alt forms weren't available :
- [ ] Spiked-Ear for Pichu
- [ ] Armored (Mewtwo)
- [ ] Suprise (Togepi and line)
- [ ] Christmas (Santa, Elf, Grinch)
- [ ] Castform
- [ ] Deoxys
- [ ] Cherrim
- [ ] Rotom
- [ ] Black for Kyurem
- [ ] Vivillon
- [ ] Furfrou
- [ ] Basculin
- [ ] Flabébé/Floette/Florges
- [ ] Minior
- [ ] Oricorio
- [ ] Eiscue
- [ ] Aegislash
- [ ] Pumpkaboo/Gougeist
- [ ] Lycanroc
- [ ] Wishiwashi
- [ ] Toxtricity
- [ ] Urshifu
- [ ] Zacian/Zamazenta
- [ ] Male (Indeedee)

I might have forgotten a few alt forms. If so, I'll update the list as it goes

**Comment by Aegyo** [comment]
forms that only show up once don't really get any benefit from an alt key, so I've left them out. I think from this list it is just Surprise which has more than one pokemon, I'll add that

**Comment by Razikd29** [comment]
Ok, so that leaves only :
- [ ] Surprise
- [ ] Male (for Indeedee for now, not sure if it'll ever be useful)

**Comment by Aegyo** [comment]
sure, there is male/female nidoran too

**Comment by Aegyo** [comment]
Seems like there is currently only one Surprise pokemon, so I've just added male/female
